//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToeCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToeCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida finalizada!.
        /// </summary>
        internal static string FINISHED_GAMER_MESSAGE {
            get {
                return ResourceManager.GetString("FINISHED_GAMER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoI Owww, isso é bem constrangedor para nós mas algo de grave ocorreu.   :&apos;(   Pedimos desculpas por isso e que nos envie o problema relatado para administrador@dominio.com. Detalhes do erro:.
        /// </summary>
        internal static string GENERAL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("GENERAL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimentação inválida.
        /// </summary>
        internal static string INVALID_PLAY_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_PLAY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimentação inválida!.
        /// </summary>
        internal static string INVALID_POSITION_MOVEMENT {
            get {
                return ResourceManager.GetString("INVALID_POSITION_MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar acessar sua partida !!! :(  Isso é bem constrangedor para nós !!!  Pedimos desculpas.  Envie um e-mail para administrador@dominio.com relatando o ocorrido e inclua também as seguintes informações:.
        /// </summary>
        internal static string IO_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("IO_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida não encontrada.
        /// </summary>
        internal static string IO_NOT_FOUNT_FILE_MESSAGE {
            get {
                return ResourceManager.GetString("IO_NOT_FOUNT_FILE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é turno do jogador.
        /// </summary>
        internal static string PLAYER_TURN_VALIDATION_MESSAGE {
            get {
                return ResourceManager.GetString("PLAYER_TURN_VALIDATION_MESSAGE", resourceCulture);
            }
        }
    }
}
